# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_1_joint:
#    has_position_limits: false
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 50.0
    has_effort_limits: true
    max_effort: 5.0
  arm_2_joint:
#    has_position_limits: false
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 50.0
    has_effort_limits: true
    max_effort: 5.0
  arm_3_joint:
#    has_position_limits: false
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 50.0
    has_effort_limits: true
    max_effort: 5.0
  arm_4_joint:
#    has_position_limits: false
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 50.0
    has_effort_limits: true
    max_effort: 5.0
  arm_5_joint:
#    has_position_limits: false
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 50.0
    has_effort_limits: true
    max_effort: 5.0
  arm_6_joint:
#    has_position_limits: false
#    min_position: -2.0943951
#    max_position: 2.0943951
    has_velocity_limits: true
    max_velocity: 0.25
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 50.0
    has_effort_limits: true
    max_effort: 5.0
  arm_7_joint:
#    has_position_limits: false
#    min_position: -2.0943951
#    max_position: 2.0943951
    has_velocity_limits: true
    max_velocity: 0.25
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 50.0
    has_effort_limits: true
    max_effort: 5.0
