#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]


group1:
  group_name: gripper
  component_name: gripper
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [halt,trigger,halt]]

group2:
  group_name: gripper
  component_name: gripper
  buttons: [[home,move,home],
    [closed,move,closed],
    [open,move,open]]
